### ISSUE TITLE
KeyError with discourse

### ISSUE THREAD

**Issue by m-sinclair** [Ontodia/ckanext-discourse#17]
CKAN 2.41
psql (PostgreSQL) 9.1.19
Standard source deployment

I recieve the following error after running $python setup.py

[Sun Nov 22 22:35:14 2015] [error]   Traceback (most recent call last):
[Sun Nov 22 22:35:14 2015] [error]     File "/usr/lib/python2.7/site.py", line 157, in addpackage
[Sun Nov 22 22:35:14 2015] [error]       exec line
[Sun Nov 22 22:35:14 2015] [error]     File "<string>", line 1, in <module>
[Sun Nov 22 22:35:14 2015] [error]   KeyError: 'ckanext'
[Sun Nov 22 22:35:14 2015] [error] 
[Sun Nov 22 22:35:14 2015] [error] Remainder of file ignored

**Comment by m-sinclair** [comment]
Unrelated issue from separate plugin.
